### ISSUE TITLE
add instructions for including library via jitpack

### ISSUE THREAD

**Issue by dbachelder** [antwankakki/FabricView#4]
https://jitpack.io/#antwankakki/FabricView/27cff2ef00

**Comment by antwankakki** [comment]
I don't know when it will be appropriate to do that as the library is still in its infancy and lacks a lot. For now, I feel like it would be better if whoever wants to use it actually goes thorough and clones it to see its internals rather than referencing it. But again, this is the first time I publish a library so I am not sure when exactly to do so.

**Comment by dbachelder** [comment]
as long as it's clear this is alpha.. I think it's fine.. but obviously it's your call. I'm using jitpack to play around with it in a project now. works great!

**Comment by antwankakki** [comment]
Thanks! Will add them right now

**Comment by antwankakki** [comment]
*as soon as I get home
